site_stage/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('scratch/', include('stage_scratch.urls')),
    path('', RedirectView.as_view(url='scratch/')),
]

stage_scratch/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.views.generic import RedirectView


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('concept/<str:concept_name>', views.concept, name='concept'),
    path('test', views.test, name='test'),
    path('scratch', views.scratchOffline, name='scratchOffline'),
    path('slide', views.slide, name='slide'),
    path('project/<str:project_name>', views.project, name='project'),
    path('myProject', views.myProject, name='myProject'),
    # path('locale/<str:fileName>', views.locale),
]

stage_scratch/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



class Category(models.Model):
    categoryName = models.CharField(max_length=50, help_text="Texte/titre de la catégorie")

    def __str__(self):
        return "Categorie " + self.categoryName


class Concept(models.Model):
    conceptName = models.CharField(max_length=100, help_text="Titre du concept")
    conceptNumber = models.IntegerField(unique=True, blank=True, null=True, help_text="Numéro du concept (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    conceptPreBlocksDescription = models.TextField(default="", help_text="Description courte avant que les blocs soit données")
    conceptPostBlocksDescription = models.TextField(default="", blank=True, null=True, help_text="Description après que les blocs soit données")
    conceptIcon = models.CharField(max_length=50, null=True, blank=True, help_text="Nom de l'image utilisé comme icone pour ce concept (dans img/icons/concept/ )")

    def __str__(self):
        return self.conceptName


class ConceptExample(models.Model):
    exampleName = models.CharField(max_length=100, help_text="Titre de l'exemple")
    exampleConcept = models.ForeignKey(Concept, null=True, on_delete=models.SET_NULL, help_text="Concept auquel est attaché cet exemple")
    exampleNumber = models.IntegerField(default=0, help_text="Numéro de l'exemple (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    exampleBlocks = models.TextField(null=True, help_text="Blocs utilisés pour la réalisation de l'exemple")
    exampleText = models.TextField(help_text="Description de l'exemple")
    exampleOnlineProjectId = models.IntegerField(null=True, help_text="ID utilisé sur le site de scratch pour une démo de l'exemple")
    exampleScratchFile = models.CharField(blank=True, null=True, max_length=50, help_text="Nom du fichier scratch (sans .sb2) situé dans '/static/scratch/files/examples'")

    def __str__(self):
        return "Exemple " + str(self.exampleNumber) + " de " + str(self.exampleConcept) + " : " + self.exampleName


class ConceptExercise(models.Model):
    exerciseName = models.CharField(max_length=100, help_text="Titre de l'exercice")
    exerciseConcept = models.ForeignKey(Concept, null=True, on_delete=models.SET_NULL, help_text="Concept auquel est lié cet exercice")
    exerciseNumber = models.IntegerField(help_text="Numéro de l'exercice (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    exerciseStatement = models.TextField(help_text="enoncé de l'exercice")
    exerciseBest = models.BooleanField(default=False, help_text="Meilleur exercice")
    exerciseOnlineProjectId = models.IntegerField(null=True, blank=True, help_text="ID utilisé sur le site de scratch pour une démo de l'exercice (facultatif)")
    exerciseScratchFile = models.CharField(blank=True, null=True, max_length=50, help_text="Nom du fichier scratch (sans .sb2) situé dans '/static/scratch/files/exercices'")
    exerciceSolution = models.TextField(default="", help_text="Solution de l'exercice")

    def __str__(self):
        return "Ex "+str(self.exerciseNumber)+ ' (' + str(self.exerciseConcept) + ')'+" : "+self.exerciseName


class ConceptExerciseHint(models.Model):
    hintExercise = models.ForeignKey(ConceptExercise, null=True, on_delete=models.SET_NULL, help_text="Exercice auquel cet indicé est lié")
    hintNumber = models.IntegerField(help_text="Numéro de l'indice (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    hintContent = models.TextField(help_text="Contenu textuel de l'indice")

    def __str__(self):
        return "indice " + str(self.hintNumber) + " de " + str(self.hintExercise)


class Slide(models.Model):
    slideTitle = models.CharField(max_length=50, help_text="Titre des slides")
    slideLink = models.CharField(max_length=150, help_text="partie distincte de l'URL menant vers les slides en ligne")
    slideNumber = models.IntegerField(help_text="Numéro de la slide (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    slideRelatedConcept = models.ForeignKey(Concept, null=True, blank=True, on_delete=models.SET_NULL, help_text="Concept pour le quel les slides s'applique")
    slideCategory = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, help_text="Catégorie de la slide")

    def __str__(self):
        return "Slide " + self.slideTitle


class Project(models.Model):
    projectTitle = models.CharField(max_length=50, help_text="Titre/Nom du projet")
    projectThumbnail = models.CharField(max_length=50, help_text="Nom de l'aperçu du projet dans static/img/projectsPreview")
    projectSummary = models.TextField(help_text="Court texte de description du project")
    projectOnlineProjectId = models.IntegerField(null=True, help_text="ID utilisé sur le site de scratch pour une démo du projet")
    projectScratchFile = models.CharField(blank=True, null=True, max_length=50, help_text="Nom du fichier scratch (sans .sb2) situé dans '/static/scratch/files/projects'")
    projectGameGoal = models.TextField(help_text="Définir l'ensemble des règles du jeu")
    projectDifficulty = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(10), MinValueValidator(0)], help_text="Difficulté de réalisation du projet (note sur 10)")

    def __str__(self):
        return "Project " + self.projectTitle


class ProjectSprite(models.Model):
    projectSpriteName = models.CharField(max_length=50, help_text="Nom du lutin")
    projectSpriteRelatedProject = models.ForeignKey(Project, null=True, on_delete=models.SET_NULL, help_text="Projet auquel ce lutin est lié")

    def __str__(self):
        return "Sprite " + self.projectSpriteName + " (" + str(self.projectSpriteRelatedProject) + ")"


class ProjectSpriteObjective(models.Model):
    projectSpriteObjectiveTitle = models.CharField(max_length=50, help_text="Titre/Nom de l'objectif")
    projectSpriteObjectiveNumber = models.IntegerField(help_text="Numéro de l'objectif (pas grave s'ils ne se suivent pas, ils servent pour donner un ordre logique)")
    projectSpriteObjectiveRelatedProjectSprite = models.ForeignKey(ProjectSprite, null=True, on_delete=models.SET_NULL, help_text="Sprite du projet auquel cet objectif de lutin est lié")
    projectSpriteObjectiveExplanation = models.TextField(help_text="Détail sur l'objectif")

    def __str__(self):
        return "Sprite Objective " + self.projectSpriteObjectiveTitle + "("+str(self.projectSpriteObjectiveRelatedProjectSprite)+")"


class ScratchBlock(models.Model):
    blockJson = models.TextField(max_length=200, help_text="Voir : https://github.com/scratchblocks/scratchblocks/blob/master/locales/fr.json")
    blockDescription = models.TextField(help_text="Description du bloc")
    relatedConcept = models.ForeignKey(Concept, null=True, blank=True, on_delete=models.SET_NULL, help_text="Concept nécessitant l'utilisation de ce bloc")
    additionalBlocks = models.ManyToManyField(ConceptExercise, blank=True, help_text="Blocs additionnels d'un exercice n'ayant pas encore vu au stade du chapitre courant")
    helpBlocks = models.ManyToManyField(ProjectSpriteObjective, blank=True, help_text="Blocs pour aider à guider lors de la réalisation d'un projet")
    # scratchDocumentationLinkName = models.CharField(max_length=150, null=True, blank=True, help_text="Nom dans l'url tel que définit sur le wiki de scratch : https://fr.scratch-wiki.info/wiki/Cat%C3%A9gorie:Blocs")
    # déterminable en utilisant le Json du bloc

    def __str__(self):
        return "Bloc : " +str(self.blockJson)

stage_scratch/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.templatetags.static import static
from django.shortcuts import redirect


from .models import *


def index(request):
    context = {
        'allConceptName': getAllconceptsName(),
        'concepts' : Concept.objects.all(),
        'projects' : Project.objects.all(),
    }
    return render(request, 'index.html', context)


def getAllconceptsName():
    return tuple(Concept.objects.values_list('conceptName', flat=True))

def isLocalhost(request):
    host = request.get_host()
    return host.startswith('127.0.0.1') or host.startswith('localhost')

def concept(request, concept_name):
    conceptInfo = get_object_or_404(Concept, conceptName=concept_name)
    conceptBlocks = conceptInfo.scratchblock_set.all()
    conceptExamples = conceptInfo.conceptexample_set.all()
    conceptExercises = conceptInfo.conceptexercise_set.all()

    nextConcept = Concept.objects.filter(id__gt=conceptInfo.id).order_by('id')[:1].first()
    lastConcept = Concept.objects.filter(id__lt=conceptInfo.id).order_by('-id')[:1].first()
    nextConceptName = None
    if nextConcept != None:
        nextConceptName = nextConcept.conceptName
    lastConceptName = None
    if lastConcept != None:
        lastConceptName = lastConcept.conceptName

    localhost = isLocalhost(request)

    context = {
        'allConceptName' : getAllconceptsName(),
        'concept' : conceptInfo,
        'conceptBlocks' : conceptBlocks,
        'conceptExamples' : conceptExamples,
        'conceptExercises' : conceptExercises,
        'conceptNext' : nextConceptName,
        'conceptLast' : lastConceptName,
        'admin' : localhost,
    }
    return render(request, 'concept.html', context)


def myProject(request):
    context = {
        'allConceptName': getAllconceptsName(),
    }
    return render(request, 'projectCustom.html', context)


def project(request, project_name):
    project = get_object_or_404(Project, projectTitle=project_name)
    projectSprites = project.projectsprite_set.all()
    context = {
        'allConceptName': getAllconceptsName(),
        'project': project,
        'projectSprites': projectSprites,
        'admin': isLocalhost(request),
    }
    return render(request, 'project.html', context)

def slide(request):
    slides = Slide.objects.all() # TODO : mettre dans l'ordre croissant des numéros
    slideCategories = slides.select_related('slideCategory').values('slideCategory__categoryName').distinct()
    context = {
        'allConceptName': getAllconceptsName(),
        'allSlides': slides,
        'slideCategories': slideCategories,
    }
    return render(request, 'slide.html', context)


def scratchOffline(request):
    context = {
    }
    return render(request, 'scratch.html', context)


def locale(request, fileName):
    staticPath = static("scratch/locale/")+fileName # Nécessaire car pas facile de changer le code de Scratch
    return redirect(staticPath)


def test(request):
    context = {
        'testStringPicture' : "Salut j'ai une imace juste ici  [img]blocs_orientations.PNG[/img] qui est dans static",
        'testStringSpoiler' : "Spoiler : [spoil title=titre id=eza] Secret secret [img]blocs_orientations.PNG[/img] [/spoil] dingue",
        'testEmbedScratchProject' : "¨Projet Scratch : [/scratchProject=237288850] cool huh ?"
    }
    return render(request, 'test.html', context)

stage_scratch/templates/concept.html
{% extends 'base.html' %}
{% block title %}Concepte | {{ concept.conceptName }}{% endblock title %}
{% block nav-style %}mkt-nav{% endblock nav-style %}

{% load static %}
{% load extraTags %}

{% block content %}
    <pre class="blocks"></pre> <!-- Je sais pas pourquoi, mais les blocs ne se montre pas bien sans ça -->

    {% if admin %}
        <p class="text-muted lead hideIfNotAdmin">Vous êtes sur la page des concept comme administrateur, tu pourra voir les solutions aux exercices et accéder aux codes sources des projets Scratch</p>
    {% endif  %}
    <h1 class="mt-5"> <img class="header-icn" src="{% static "img/icons/concept/"|add:concept.conceptIcon %}"/> {{ concept.conceptName }} </h1>

    <h4>{{ concept.conceptPreBlocksDescription|replaceBBCode|safe|linebreaks }}</h4>

    {% autoescape off %}
        {% spoil "Blocs" conceptBlocks|createBlocksTable|linebreaks %}
    {% endautoescape %}

    {{ concept.conceptPostBlocksDescription|replaceBBCode|safe }}

    <h3> Exemples </h3>
    <div class="accordion" id="accordionExamples">
        {% for example in conceptExamples %}
            <div class="card">
                <div class="card-header" data-toggle="collapse" data-target="#collapseExample{{ forloop.counter }}">
                    <h6 class="mb-0">
                        <button class="btn btn-link" type="button">
                            Exemple {{ forloop.counter }} : {{ example.exampleName}}
                        </button >
                    </h6>
                </div>
                <div id="collapseExample{{ forloop.counter }}" class="collapse" data-parent="#accordionExamples">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                {# If an offline file version is available, displays it #}
                                {% if not example.exampleScratchFile  %}
                                    {{ example.exampleOnlineProjectId|scratchOnlineProject|safe }}
                                {% elif example.exampleScratchFile %}
                                    {% autoescape off %}
                                        {% scratchOfflineProject example.exampleScratchFile "examples" %}
                                    {% endautoescape %}
                                {% endif %}
                            </div>
                            <div class="col-sm-6">
                                {{ example.exampleBlocks|scratchBlocks|safe }}
                                {{ example.exampleText|replaceBBCode|safe|linebreaks }}
                                {% if admin %}
                                    {% if example.exampleOnlineProjectId %}
                                        <a class="btn btn-info hideIfNotAdmin" href="{{ example.exampleOnlineProjectId|onlineProjectLink }}" target="_blank" role="button">Consulter en ligne</a>
                                    {% endif %}
                                    {% if example.exampleScratchFile %}
                                        <a class="btn btn-info hideIfNotAdmin" onclick="loadFile($(this).parent().parent().find('embed')[0])" role="button">Re-charger le projet</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    <h3>Défis</h3>
    <div class="accordion" id="accordionExercises">
        {% for exercise in conceptExercises %}
            <div class="card">
                <div class="card-header" data-toggle="collapse" data-target="#collapseExercise{{ forloop.counter }}">
                    <div class="row">
                        <div class="col-md-6">
                            <h6>
                                <button class="btn btn-link" type="button">
                                    Défi {{ forloop.counter }} : {{ exercise.exerciseName}}
                                </button>
                            </h6>
                        </div>
                        <div class="col-md-6">
                            <div class="text-right"> <h4>
                            {% if exercise.exerciseOnlineProjectId or exercise.exerciseScratchFile %}
                                <p class="text-success" style="display:inline">⚑</p>
                            {% endif %}
                            {% if exercise.exerciseBest %}
                                <p class="text-warning" style="display:inline">★</p>
                            {% endif %}
                        </h4></div>
                        </div>
                    </div>
                </div>
                <div id="collapseExercise{{ forloop.counter }}" class="collapse" data-parent="#accordionExercises">
                    <div class="card-body">
                        {{ exercise.exerciseStatement|replaceBBCode|safe|linebreaks }}

                        {# Additional blocks template if needed #}
                        {% if exercise.scratchblock_set.all%}
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-text">Les blocs suivants te seront utiles pour résoudre cet exercice :</p>
                                    <div id="collapseBlock" class="card">
                                        <div class="card-body">
                                            {{ exercise.scratchblock_set.all | createBlocksTable | safe }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                        {# Demo preview if given (offline try first, if not given try online) #}
                        {% if exercise.exerciseScratchFile %}
                            {% autoescape off %}
                                {% startSpoil "Démo" "DemoEx"|addStr:forloop.counter %}
                                    {% scratchOfflineProject exercise.exerciseScratchFile "exercices" %}
                                    {% if admin %}
                                        <a class="btn btn-info hideIfNotAdmin" onclick="toggleEdition($(this).parent().find('embed')[0])" role="button">Toggle édition</a>
                                    {% endif %}
                                <a class="btn btn-info" onclick="loadFile($(this).parent().find('embed')[0])" role="button">Re-charger le projet</a>
                                {% stopSpoil %}
                            {% endautoescape %}
                        {% elif exercise.exerciseOnlineProjectId %}
                            {% autoescape off %}
                                {% spoil "Démo" exercise.exerciseOnlineProjectId|scratchOnlineProject|safe %}
                                {% if admin %}
                                    <a class="btn btn-info hideIfNotAdmin" href="{{ exercise.exerciseOnlineProjectId|onlineProjectLink }}" target="_blank" role="button">Consulter en ligne</a>
                                {% endif %}
                            {% endautoescape %}
                        {% endif  %}

                        {# Hints for the current exercice (no need for accordions as several can be opend at once) #}
                        {% autoescape off %}
                            {% for hint in exercise.conceptexercisehint_set.all|orderQueryBy:"hintNumber" %}
                                {% spoil "Indice "|addStr:forloop.counter hint.hintContent|replaceBBCode|safe|linebreaks False "hint"|addStr:forloop.counter|addStr:"ex"|addStr:forloop.parentloop.counter%}
                            {% endfor %}
                        {% endautoescape %}

                        {% if admin and exercise.exerciceSolution %}
                            <div class="hideIfNotAdmin">
                            {% autoescape off %}
                                {% spoil "Solution" exercise.exerciceSolution|scratchBlocks|safe %}
                            {% endautoescape %}
                            </div>
                        {% endif  %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {# Buttons to previous and next section #}
    <nav aria-label="NextPreviousConcept">
        <ul class="pagination justify-content-center">
            {% if conceptLast != None %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'concept' conceptLast %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">&laquo; {{ conceptLast }}</a>
                </li>
            {% endif %}

            {% if conceptNext != None %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'concept' conceptNext %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">{{ conceptNext }} &raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endblock content %}

stage_scratch/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}

{% load static %}
{% load extraTags %}


{% block content %}
    <h1><img class="header-icn" src="{% static "img/icons/concept.svg" %}"/> Concepts </h1>
    <ul class="list-group ">
        {% for concept in concepts %}
            <li class="list-group-item">
                <h3><img class="header-icn" src="{% static "img/icons/concept/"|add:concept.conceptIcon %}"/> <a href="{% url 'concept' concept.conceptName %}">{{ concept.conceptName }}</h3></a>
                <p class="text-muted">{{ concept.conceptPreBlocksDescription|replaceBBCode|safe }}</p>
            </li>
        {% endfor %}
    </ul>

    <h1><img class="header-icn" src="{% static "img/icons/slide.png" %}"/> Slides de présentation</h1>
    <p>Toutes les slides présentés pendant le cours (et plus) sont disponible sur ce  <a href="{% url "slide" %}">LIEN</a></p>


    <h1><img class="header-icn" src="{% static "img/icons/games.png" %}"/> Idées de jeux </h1>

    <div class="d-flex justify-content-center">
        <a href="{% url 'myProject' %}" class="card text-dark mb-4" style="width: 18rem;text-decoration: none;">
            <img class="card-img-top" src="{% static "img/projectsPreview/projetInconnu.png" %}" alt="Projet personnel">
            <div class="card-body">
                <h5 class="card-title">Comment faire un projet personnel ?</h5>
                <p class="card-text">Jette un oeil ici pour commencer un nouveau projet ! Pleins de conseils et astuce pour bien réussir ;)</p>
            </div>
        </a>
    </div>

    <div class="card-deck">

        {% for project in projects|orderQueryBy:'projectDifficulty' %}
{#            <a href="{% url 'project' project.projectTitle %}">#}
                <a href="{% url 'project' project.projectTitle %}" class="card text-dark mb-4" style="width: 18rem;text-decoration: none;">
                    {% with "img/projectsPreview/"|add:project.projectThumbnail as imgUrl %}
                        <img class="card-img-top" src="{% static imgUrl %}" alt="{{ project.projectTitle }}">
                    {% endwith %}
                    <div class="card-body">
                        <h5 class="card-title">{{ project.projectTitle }}</h5>
                        <p class="card-text">{{ project.projectSummary }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Difficulté : {{ project.projectDifficulty }}/10</small>
                    </div>
                </a>
                {% if forloop.counter|add:0|divisibleby:4 %} {# On saute une ligne tout les i % ... #}
                    <div class="w-100 d-none d-xl-block"></div>
                {% endif %}

{#            </a>#}
        {% endfor %}
    </div>

{% endblock content %}

stage_scratch/templates/project.html
{% extends 'base.html' %}
{% block title %}Project{% endblock title %}

{% load static %}
{% load extraTags %}

{% block content %}
    {# TODO : ajouter les concepts nécessaires à la réalisation du projet (coordonnées, orientation, etc.) #}
    {% if admin %}
        <p class="text-muted lead hideIfNotAdmin">Vous êtes sur la page des projets comme administrateur</p>
    {% endif %}

    <h1> {{ project.projectTitle }} </h1>
    <p class="text-muted">{{ project.projectSummary }}</p>

    <h2 id="resume">Résumé</h2>
    <p>{{ project.projectGameGoal|linebreaks }}</p>


    <h2>Démo</h2>
{#    {{ project.projectOnlineProjectId|scratchOnlineProject|safe }}#}
    {% autoescape off %}
        {% startSpoil "Démo" "demoProject" %}
            {% scratchOfflineProject project.projectScratchFile "projects" %}
            {% if admin %}
                <a class="btn btn-info hideIfNotAdmin" onclick="toggleEdition($(this).parent().find('embed')[0])" role="button">Toggle édition</a>
            {% endif %}
            <a class="btn btn-info" onclick="loadFile($(this).parent().find('embed')[0])" role="button">Re-charger le projet</a>
        {% stopSpoil %}
    {% endautoescape %}

    <h2>Réalisation</h2>

    <h4>Identification des objectifs du jeu</h4>
    <p>On va se poser la question de <b>qu'est ce qu'on veut ?</b></p>
    <p>( déjà répondu dans le <a href="#resume">résumé</a> )</p>

    <h4>Identification des lutins</h4>
    <p>On va se poser la question <b>de quoi avons nous besoin et que doit-il faire?</b></p>
    Dans notre cas j'ai choisi d'en utiliser {{ projectSprites|length }} :
    <ul>
        {% for projectSprite in projectSprites %}
            <li>{{ projectSprite.projectSpriteName }}</li>
        {% endfor %}
    </ul>

    <h4>Programmation des lutins </h4>
    {% for projectSprite in projectSprites %}
        <h5>{{ projectSprite.projectSpriteName }}</h5>
        {% for projectSpriteObjective in projectSprite.projectspriteobjective_set.all %}
            <h6> {{ projectSpriteObjective.projectSpriteObjectiveTitle }} </h6>
            <p> {{ projectSpriteObjective.projectSpriteObjectiveExplanation|linebreaks }} </p>
        {% endfor %}
    {% endfor %}

    {# TODO : ajouter une section sur les suggestions d'amélioration du jeu (niveau en plus, etc.) avec les concepts nécessitant l'ajout (varaibles, messages, ...) #}

    <script>
    function JSeditorReady() {
        var scratchLoadTarget = jQuery(this).find("embed");
        console.log("CALL to JSeditorReady, with target : ");
        console.log(scratchLoadTarget);

        if (scratchLoadTarget != null) {
            for (var i=0; i<scratchLoadTarget.length; i++) {
                // Load l'URL
                loadFile(scratchLoadTarget[i]);
                // Load le mode éditeur ou jeu
                loadEdition(scratchLoadTarget[i]);
            }
        } else {
            console.warn("Appel de JSeditorReady sans cible");
        }

        return true;
    }

    </script>

{% endblock content %}

stage_scratch/templates/scratch.html
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>Scratch Editor</title>

    <script>
		function JSeditorReady() {
		    /*
		    var scr = document.getElementById("scratch-flash");
		    scr.ASsetEditMode(false);
			scr.ASloadProjectUrl("{% static "scratchProjects/test.sb2" %}");
			*/
			return true;
		}
	</script>

</head>
<body leftmargin="0" topmargin="0" scroll="no">
    <embed id="scratch-flash" width="100%" height="100%" fullscreen="yes" src="{% static "scratch/Scratch.swf" %}">

{#    <object id="scratch-flash" style="display: inline; visibility: visible; position: relative; z-index: 1000;" type="application/x-shockwave-flash" height="100%" width="100%" SCALE="default">#}
{#		<param name="movie" value="{% static "scratch/Scratch.swf" %}">#}
{#		<param name="bgcolor" value="#00FFFF">#}
{#		<param name="allowScriptAccess" value="always">#}
{#		<param name="allowFullScreen" value="true">#}
{#		<param name="wmode" VALUE="direct">#}
{#		<param name="menu" VALUE="true">#}
{#	</object>#}


</body>